name: Job workflow

on:
  push:
    branches:
    - 'master'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: retrieve output
      uses: ./library 
